# Generated by Django 4.2.8 on 2025-03-12 21:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_upload", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfile",
            name="processed_content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
